<?xml version="1.0" encoding="utf-8"?><Database Name="FeelOfTravel" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=FeelOfTravel;Persist Security Info=True;User ID=sa" SettingsObjectName="FeelOfTravel.SqlDataAccess.Properties.Settings" SettingsPropertyName="FeelOfTravelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbAboutPage" Member="tbAboutPages">
    <Type Name="tbAboutPage">
      <Column Name="entryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbOfferTypes" Member="tbOfferTypes">
    <Type Name="tbOfferType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbOfferType_tbOffer" Member="tbOffers" ThisKey="id" OtherKey="typeId" Type="tbOffer" />
    </Type>
  </Table>
  <Table Name="dbo.tbContactsPage" Member="tbContactsPages">
    <Type Name="tbContactsPage">
      <Column Name="entryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbInformationCategories" Member="tbInformationCategories">
    <Type Name="tbInformationCategory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbInformationCategory_tbCoreArticleData" Member="tbCoreArticleDatas" ThisKey="id" OtherKey="categoryId" Type="tbCoreArticleData" />
    </Type>
  </Table>
  <Table Name="dbo.tbOffers" Member="tbOffers">
    <Type Name="tbOffer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="coreArticleDataId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="typeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbOfferType_tbOffer" Member="tbOfferType" ThisKey="typeId" OtherKey="id" Type="tbOfferType" IsForeignKey="true" />
      <Association Name="tbCoreArticleData_tbOffer" Member="tbCoreArticleData" ThisKey="coreArticleDataId" OtherKey="id" Type="tbCoreArticleData" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbCoreArticleData" Member="tbCoreArticleDatas">
    <Type Name="tbCoreArticleData">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="header" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="imageUrl" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="publishDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="tbCoreArticleData_tbOffer" Member="tbOffers" ThisKey="id" OtherKey="coreArticleDataId" Type="tbOffer" />
      <Association Name="tbInformationCategory_tbCoreArticleData" Member="tbInformationCategory" ThisKey="categoryId" OtherKey="id" Type="tbInformationCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>